Repository thomedpete/Dokes, pull requests merged in 2023-01, with the labels that each got.

#17 Cypress setup
  cypress.config.js
  cypress/e2e/homePage_spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  public/index.html
  src/Components/App/App.js
  src/Components/Header/Header.js
  src/Components/HeroBanner/HeroBanner.js
  src/Components/JokeCard/JokeCard.js
Labels: Testing

#25 Joke favorite button
  src/Components/App/App.js
  src/Components/JokeCard/JokeCard.js
Labels: Component, Styles, Network Requests

#30 Theme setup
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Header/Header.js
  src/Components/HeroBanner/HeroBanner.js
  src/Components/JokeCard/JokeCard.js
  src/theme.js
Labels: Chore

#34 Icon button
  src/Components/App/App.js
  src/Components/Home/Home.js
  src/Components/JokeCard/JokeCard.js
  src/Components/Pocket/Pocket.js
  src/apiCalls.js
Labels: enhancement

#35 Add delete functionality
  src/Components/App/App.js
  src/Components/Pocket/Pocket.js
Labels: enhancement

#39 Joke display
  src/Components/Header/Header.js
  src/Components/Home/Home.js
  src/Components/JokeCard/JokeCard.css
  src/Components/JokeCard/JokeCard.js
  src/theme.js
Labels: bug, Styles

#42 Adds correct testing for most homepage user flows.
  cypress/e2e/homePage_spec.cy.js
  src/Components/Header/Header.js
  src/Components/JokeCard/JokeCard.js
Labels: Testing

#54 Prop types
  src/Components/About/About.js
  src/Components/App/App.js
  src/Components/App/App.test.js
  src/Components/Header/Header.js
  src/Components/Home/Home.js
  src/Components/JokeCard/JokeCard.js
  src/Components/Pocket/Pocket.js
  src/Components/Whoopsie/Whoopsie.js
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: Chore

#59 Mobile view
  src/Components/App/App.js
  src/Components/BadURL/BadURL.js
  src/Components/Home/Home.js
  src/Components/JokeCard/JokeCard.css
  src/Components/JokeCard/JokeCard.js
  src/Components/Login/Login.css
  src/Components/Login/Login.js
  src/Components/Pocket/Pocket.css
  src/Components/Pocket/Pocket.js
  src/theme.js
Labels: Chore, Refactor, Styles

#60 Cypress error page
  cypress/e2e/errorPage.cy.js
Labels: Testing

#61 Adds breakpoint adjustments
  src/Components/JokeCard/JokeCard.js
Labels: Refactor

#62 Adds some refactoring
  src/Components/App/App.css
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Home/Home.css
  src/Components/Home/Home.js
  src/Components/JokeCard/JokeCard.css
  src/Components/JokeCard/JokeCard.js
  src/index.css
Labels: Refactor

#63 Ipad sizing
  src/Components/JokeCard/JokeCard.js
Labels: Refactor, Animations

#64 Fix iphone
  src/Components/JokeCard/JokeCard.js
  src/index.css
Labels: bug, Styles

#67 Adds padding to pocket mui container
  src/Components/Pocket/Pocket.js
Labels: Styles
